name: Merge and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Build package
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Deploy package
        run: |
          git config --global user.name ${{ secrets.ACTIONS_DEPLOY_USERNAME }}
          git config --global user.email ${{ secrets.ACTIONS_DEPLOY_EMAIL }}
          git remote set-url origin https://${{ secrets.ACTIONS_DEPLOY_USERNAME }}:${{ secrets.ACTIONS_DEPLOY_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
        env:
          user-name: ${{ secrets.ACTIONS_DEPLOY_USERNAME }}
          user-email: ${{ secrets.ACTIONS_DEPLOY_EMAIL }}
          github-token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          repository: ${{ github.repository }}